# Generated by Django 2.2 on 2019-06-04 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=8, default=50.0, max_digits=11)),
                ('longitude', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('beds', models.PositiveIntegerField(default=1)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('school', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('transport', models.DecimalField(decimal_places=8, default=0.0, max_digits=11)),
                ('property_type', models.PositiveIntegerField(default=0)),
                ('furniture_state', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('prefer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricesite.Preference')),
            ],
        ),
    ]
