# Generated by Django 2.2 on 2019-06-08 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0002_auto_20190607_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Visitor', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefer',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pricesite.Preference'),
        ),
    ]
