# Generated by Django 2.2 on 2019-07-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0005_preferencehouses'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencehouses',
            name='interest',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
