# Generated by Django 2.2 on 2019-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0007_auto_20190705_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencehouses',
            name='furniture_state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='preferencehouses',
            name='property_type',
            field=models.CharField(default='', max_length=40),
        ),
    ]
