# Generated by Django 2.2 on 2019-07-10 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0009_auto_20190709_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='prefer',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='pricesite.Preference'),
        ),
    ]
