# Generated by Django 2.2 on 2019-07-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0010_auto_20190710_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='price',
            field=models.PositiveIntegerField(default=1500),
        ),
    ]
