# Generated by Django 2.2 on 2019-07-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0011_auto_20190720_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferencehouses',
            name='postcode',
            field=models.CharField(default='', max_length=40),
        ),
    ]
