# Generated by Django 2.2 on 2019-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricesite', '0012_preferencehouses_postcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(default='Tourist', max_length=20)),
                ('name', models.CharField(default='Tourist', max_length=20)),
            ],
        ),
    ]
